# Generated by Django 5.2.7 on 2025-10-06 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='codigo_interno',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='carga_descripcion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='fecha_llegada',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='estado',
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default='Producto sin nombre', max_length=200),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultimo_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='realizado_por',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='titulo',
            field=models.CharField(default='Mantenimiento', max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ruta',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='vehiculos.perfil'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ruta',
            name='titulo',
            field=models.CharField(default='Ruta sin título', max_length=200),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible_tipo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='proveedor',
            field=models.CharField(blank=True, default='Desconocido', max_length=200),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('otros', 'Otros')], default='preventivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(default='chofer', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
