# Generated by Django 5.2.7 on 2025-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_inventario_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(default='chofer', max_length=30),
        ),
    ]
