# Generated by Django 5.2.7 on 2025-10-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_cargacombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='chofer_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='vehiculos.perfil'),
        ),
    ]
