# Generated by Django 5.2.7 on 2025-10-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_chofer_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='resetea_odometro',
            field=models.BooleanField(default=True, help_text='Marcar si este mantenimiento resetea el contador de KM'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_para_mantenimiento',
            field=models.IntegerField(blank=True, default=5000, help_text='Intervalo de KM para el próximo mantenimiento (ej: 5000)', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='km_proximo_mantenimiento',
            field=models.IntegerField(blank=True, default=5000, help_text='Odómetro del próximo mantenimiento (ej: 150000)', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='mantenimiento_requerido',
            field=models.BooleanField(default=False, help_text='Marcar si el vehículo ha pasado su KM de mantenimiento'),
        ),
    ]
