# Generated by Django 5.2.7 on 2025-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_mantenimiento_resetea_odometro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='status',
            field=models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada')], default='programada', help_text='Estado actual de la ruta', max_length=20),
        ),
    ]
