# Generated by Django 5.2.7 on 2025-10-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_ruta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='recibe_alertas_mantenimiento',
            field=models.BooleanField(default=False, help_text='Marcar si el usuario debe recibir correos de alerta de mantenimiento'),
        ),
    ]
