# Generated by Django 5.2.7 on 2025-10-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_perfil_recibe_alertas_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='odometro_anterior',
            field=models.IntegerField(blank=True, help_text='Odómetro registrado en la carga anterior para este vehículo', null=True),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='rendimiento_km_lt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendimiento calculado para este tramo (KM/Lt)', max_digits=6, null=True),
        ),
    ]
