# Generated by Django 5.2.7 on 2025-10-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_cargacombustible_odometro_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='odometro',
            field=models.IntegerField(blank=True, help_text='El kilometraje del vehículo CUANDO se hizo el mantenimiento', null=True),
        ),
    ]
