# Generated by Django 5.2.7 on 2025-10-30 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0010_mantenimiento_odometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(default=1)),
                ('item_inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_en_mantenimiento', to='vehiculos.inventario')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_items', to='vehiculos.mantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='items_usados',
            field=models.ManyToManyField(related_name='mantenimientos_asociados', through='vehiculos.DetalleMantenimiento', to='vehiculos.inventario'),
        ),
    ]
