# Generated by Django 5.2.7 on 2025-10-30 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_detallemantenimiento_mantenimiento_items_usados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Carga sin título', max_length=200)),
                ('cliente', models.CharField(blank=True, help_text='Nombre del cliente o empresa', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Asignación'), ('asignado', 'Asignado a Ruta'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del flete', max_length=20)),
                ('peso_toneladas', models.DecimalField(blank=True, decimal_places=2, help_text='Peso de la carga en toneladas', max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fletes_asignados', to='vehiculos.ruta')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
