# Generated by Django 5.2.7 on 2025-10-31 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_flete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddIndex(
            model_name='cargacombustible',
            index=models.Index(fields=['vehiculo', 'fecha'], name='vehiculos_c_vehicul_b7c5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cargacombustible',
            index=models.Index(fields=['chofer'], name='vehiculos_c_chofer__fabbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['fecha'], name='vehiculos_r_fecha_314013_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['chofer'], name='vehiculos_r_chofer__f6caed_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['vehiculo'], name='vehiculos_r_vehicul_3bbcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['chofer_asignado'], name='vehiculos_v_chofer__82a2ad_idx'),
        ),
    ]
